### ISSUE TITLE
dockerhub repo for plex?

### ISSUE THREAD

**Issue by matthewaaronthacker** [timhaak/docker-plex-old#1]
Sorry, I know this isn't really the place for this, but had no idea how else to contact you. What happened to your docker.io/timhaak/plex? I can't pull it anymore, and it kind of broke my whole setup.

**Comment by timhaak** [comment]
Hi

I was able to have the time to maintain it properly any more. 

And was starting worry that it would get further behind.

Had no idea how to move people.

All the files are here in the repository.

My recommendation would be to move the official docker image.

Or if you prefer this code. 

Clone the repository and then do your own build on docker hub.

Then just change your scripts to the new hub image name.

Please don't build off of this git hub repository as I will be removing it.

**Comment by matthewaaronthacker** [comment]
Thanks. Any idea if all the parameters are the same between your container and the official?

**Comment by timhaak** [comment]
Not really.

The simple things that I was doing transferred perfectly.

Though I know there were some things to change some of the more exotic settings in this one.

**Comment by matthewaaronthacker** [comment]
Thanks again!
